name: Gym Slot Booker

on:
  schedule:
    # Runs at 2:58 PM IST every day.
    # IST is UTC+5:30.
    # 2:58 PM IST = 14:58 IST
    # 14:58 IST - 5 hours 30 minutes = 09:28 UTC
    - cron: '28 9 * * *'
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  book_gym_slot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install google-chrome-stable -y

    - name: Run Gym Booking Script
      env:
        # Pass secrets as environment variables to the Python script
        GITAM_USER_ID: ${{ secrets.GITAM_USER_ID }}
        GITAM_PASSWORD: ${{ secrets.GITAM_PASSWORD }}
        CAPTCHA_API_KEY: ${{ secrets.CAPTCHA_API_KEY }}
      run: python src/gym_booking.py